config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :blogs
  resources :events
  resources :categories, only: [:show]
  resources :participations, only: [:new]
  resources :connections, only: [:new]

  resources :conversations do
    resources :messages
  end

  devise_for :users
  resources :users, only: [:show]

  get 'welcome/index'
  get 'about', to: 'welcome#about'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :events
  has_many :participations
  has_many :events, through: :participations
  has_many :blogs

  has_one_attached :image

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    first_name + ' ' + last_name
  end

  def image_url
    if image.attached?
      url_for(image)
    else
      '/images/user.png'
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:show]

  def show
    senders = Connection.where(recipient_id: @user.id).map(&:sender_id)
    recipients = Connection.where(sender_id: @user.id).map(&:recipient_id)
    friends_ids = senders + recipients
    @friends = User.find(friends_ids)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:id)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/show.html.erb
<section class="page-content header-border">
  <div class="container">
    <div class="profile-image-sec">
      <div class="profile-div">
        <div class="col-md-5 float-left marg-0">
            <img src=<%= @user.image_url %> alt="">
        </div>
        <div class="col-md-7 float-left marg-0">
          <div class="profile-div1">
            <h3><%= @user.full_name %></h3>
            <h4><%= @user.title %></h4>
            <p><%= @user.description %></p>
            <!-- <div class="profile-share-div">
              <div class="row">
                <div class="col-md-6">
                  <i class="fa fa-comment-o" aria-hidden="true"></i>
                  24
                </div>
                <div class="col-md-6 text-right">Share <a href="https://instagram.com" target="_blank" title="Instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a> <a href="https://youtube.com" target="_blank" title="Youtube"><i class="fa fa-youtube" aria-hidden="true"></i></a></div>
              </div>
            </div>
            <p class="social-icons"><a href="https://instagram.com" target="_blank" title="Instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a> <a href="https://youtube.com" target="_blank" title="Youtube"><i class="fa fa-youtube" aria-hidden="true"></i></a></p> -->
          </div>
          <div class="profile-buttons mt-5">
            <div class="col-md-6 marg-0 float-left"><a href="#" class="black-btn"><%= @user.participations.length %> Joined</a></div>
            <div class="col-md-6 marg-0 float-left connect-button">
              <% if @user.id == current_user.id || Connection.where('(sender_id=? AND recipient_id=?) OR (sender_id=? AND recipient_id=?)', current_user.id, @user.id, @user.id, current_user.id).any? %>
                <p class='pink-btn'>Connected</p>
              <% else %>
                <%= link_to 'Connect', new_connection_path(sender_id: current_user.id, recipient_id: @user.id), remote: true, class: 'pink-btn' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <section class="freinds-sec">
      <section class="row effects">
        <% @friends.each do |friend| %>
          <div class="col-md-3">
            <div class="demo">
              <figure class="imghvr-fade"><img src=<%= friend.image_url %> alt="">
                <figcaption>
                  <div class="row">
                    <div class="col-md-4 text-center"><a href="https://instagram.com" target="_blank" title="Instagram"><img src="/images/instagram1.png" alt="Instagram"></a></div>
                    <div class="col-md-4 text-center"><a href="https://youtube.com" target="_blank" title="Youtube"><img src="/images/youtube.png" alt="Youtube"></a></div>
                    <div class="col-md-4 text-center"><a href="#" title="Message"><img src="/images/message.png" alt="Message"></a></div>
                  </div>
                </figcaption>
              </figure>
              <div class="member-name">
                <h4><%= friend.full_name %></h4>
                <h5><%= friend.title %></h5>
              </div>
            </div>
          </div>
        <% end %>
      </section>
    </section>
  </div>
</section>
<div class="container">
  <section class="ome-join row m-0">
    <div class="col-lg-8 col-md-6 offset-lg-1">
      <h3>Follow Omecto</h3>
    </div>
    <div class="col-lg-3 col-md-6 social-links"> <a href="#"><i class="fa fa-instagram"></i></a> <a href="#"><i class="fa fa-youtube"></i></a></div>
  </section>
</div>
<section class="post-carousel">
  <div class="container-fluid">
    <h2>Want to do more of what you love?</h2>
    <div class="slider responsive">
      <div>
        <div class="post-block">
          <div class="post-c-image"><a href="#"><img src="/images/post-thub.jpg" alt=""></a></div>
          <div class="post-c-text">
            <h3><a href="#">Discover events</a></h3>
            <p>See who’s hosting local events for all the
              things you love.</p>
            <h5><a href="#">JOIN OMECTO</a></h5>
          </div>
        </div>
      </div>
      <div>
        <div class="post-block">
          <div class="post-c-image"><a href="#"><img src="/images/post-thub2.jpg" alt=""></a></div>
          <div class="post-c-text">
            <h3><a href="#">Start an Event</a></h3>
            <p>Create your own event, and draw
              from a community of millions.</p>
            <h5><a href="#">start an event</a></h5>
          </div>
        </div>
      </div>
      <div>
        <div class="post-block">
          <div class="post-c-image"><a href="#"><img src="/images/post-thub.jpg" alt=""></a></div>
          <div class="post-c-text">
            <h3><a href="#">Discover events</a></h3>
            <p>See who’s hosting local events for all the
              things you love.</p>
            <h5><a href="#">JOIN OMECTO</a></h5>
          </div>
        </div>
      </div>
      <div>
        <div class="post-block">
          <div class="post-c-image"><a href="#"><img src="/images/post-thub2.jpg" alt=""></a></div>
          <div class="post-c-text">
            <h3><a href="#">Start an Event</a></h3>
            <p>Create your own event, and draw
              from a community of millions.</p>
            <h5><a href="#">start an event</a></h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section-follow">
  <div class="container">
    <h3>Follow Omecto</h3>
    <div class="follow"> <a href="#"><img src="/images/utube.png" alt=""></a> <a href="#"><img src="/images/instagram.png" alt=""></a> </div>
  </div>
</section>