config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :blogs
  resources :events
  resources :categories, only: [:show]
  resources :participations, only: [:new]
  resources :connections, only: [:new]

  resources :conversations do
    resources :messages
  end

  devise_for :users
  resources :users, only: [:show]

  get 'welcome/index'
  get 'about', to: 'welcome#about'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :user

  has_many :participations
  has_many :users, through: :participations

  belongs_to :location
  accepts_nested_attributes_for :location

  has_many :event_categories
  has_many :categories, through: :event_categories
  accepts_nested_attributes_for :event_categories

  has_one_attached :image
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /events
  # GET /events.json
  def index
    ip = request.remote_ip
    ip = '83.220.236.196' if ip == '::1'
    location = Geocoder.search(ip).first
    city = location.city + ', ' + location.country

    @participations = Participation.all

    category = params[:category]

    if params['distance'].nil?
      @word = ''
      @distance = 20_000
      @city = city
      @events = select_events_for @word, @distance, @city, category
    else
      @word = params[:word]
      @distance = params[:distance]

      @city = if params[:city] == ''
                city
              else
                params[:city]
              end

      @events = select_events_for @word, @distance, @city, category

      respond_to do |format|
        format.js { render 'events/update_view' }
      end
    end

    @distances = {
      '5 КМ' => 5,
      '10 КМ' => 10,
      '25 КМ' => 25,
      '50 КМ' => 50,
      '100 КМ' => 100,
      '150 КМ' => 150,
      '> 150 КМ' => 20_000
    }
  end

  def select_events_for(word, distance, city, category)
    location_ids = []

    Location.near(city, distance, units: :km).each do |location|
      location_ids << location.id
    end

    temp = Event.where('lower(title) LIKE ? OR lower(description) LIKE ?', "%#{word.downcase}%", "%#{word.downcase}%")

    if category
      events_ids = []
      event_categories = EventCategory.where(category_id: category).each { |item| events_ids << item.event_id }

      if event_categories.any?
        temp = temp.where(id: events_ids)
      end
    end

    temp.where(location_id: location_ids)
  end

  # GET /events/1
  # GET /events/1.json
  def show; end

  # GET /events/new
  def new
    @event = Event.new
    @event.build_location
    @event.event_categories.build
    @categories = Category.all
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:title, :categories, :description, :address, :date, :user_id, :image, :location_id, location_attributes: [:city], event_categories_attributes: %i[id category_id])
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/views/events/_events.html.erb
      <ul class="row categories-all">
        <% @events.each do |event| %>
          <li class="col-lg-4 col-md-4 col-sm-6">
            <div class="cat-wrap">
              <a href="" data-toggle="modal" data-target="#event<%= event.id %>">
                <% if event.image.attached? %>
                  <img src=<%= url_for(event.image) %> alt="">
                <% else %>
                  <img src='/images/city<%= rand(30) + 1 %>.jpg' alt="">
                <% end %>
                <a class="zoom1" href="">
                  <img src="/images/zoom.png" alt="">
                </a>
                <div class="hover1">
                  <a href="" data-toggle="modal" data-target="#event<%= event.id %>">
                    <%= event.title %>
                  </a>
                  <%= event.users.length + 1 %> members
                </div>
              </a>
            </div>
          </li>
        <% end %>
      </ul>

app/views/events/_form.html.erb
<section class="blog-single event-creation1">
  <div class="container">
      <div class="blog-details">
        <article class="event-creation">

          <%= form_with(model: event, local: true) do |form| %>
            <h5>What do you want to do</h5>

            <% if event.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

                <ul>
                <% event.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <%= form.text_field :title, class: "form-control", placeholder: "Name your social, make it descriptive!" %>

            <h5>What's your socials about Select up to 2 Categories.</h5>
            <p class="red">Choose at least one category</p>
            <div class="icons-sec">
              <div class="row">
                <% @categories.each do |category| %>
                    <div class="col-sm-6 border">
                    <div class="row">
                      <div class="col-md-2 col-3 icon-img"><img src=<%= category.icon %> alt=""></div>
                      <div class="col-md-8 col-7"><%= category.title %></div>
                      <div class="col-md-2 col-2">
                        <%= check_box_tag 'event[event_categories_attributes][][category_id]', category.id, false, class: "category-box" %>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>

            <%= form.text_field :user_id, type: :hidden, value: current_user.id %>

            <%= form.text_area :description, class: "form-control", placeholder: "Tell us more about your social" %>

            <%= form.fields_for :location do |location_form| %>
              <%= location_form.text_field :city, placeholder: "City", class: "form-control", id: 'searchTextField' %>
            <% end %>

            <%= form.text_field :address, placeholder: "Pick A Venue", class: "form-control" %>

            <%= form.file_field :image, class: "form-control" %>

            <%= form.datetime_select :date, placeholder: "Enter a Date", class: "form-control" %>

            <div class="actions">
              <%= form.submit %>
            </div>
          <% end %>

        </article>
      </div>
      <section class="ome-join row m-0">
        <div class="col-lg-8 col-md-6 offset-lg-1">
          <h3>Find and Join Social</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
            Aenean euismod bibendum laoreet.</p>
        </div>
        <div class="col-lg-3 col-md-6 social-links"> <a href="#"><i class="fa fa-instagram"></i></a> <a href="#"><i class="fa fa-youtube"></i></a></div>
      </section>
    </div>
</section>
<section class="post-carousel">
  <div class="container-fluid">
    <h2>Want to do more of what you love?</h2>
    <div class="slider responsive">
      <div>
        <div class="post-block">
          <div class="post-c-image"><a href="#"><img src="/images/post-thub.jpg" alt=""></a></div>
          <div class="post-c-text">
            <h3><a href="#">Discover events</a></h3>
            <p>See who’s hosting local events for all the
              things you love.</p>
            <h5><a href="#">JOIN OMECTO</a></h5>
          </div>
        </div>
      </div>
      <div>
        <div class="post-block">
          <div class="post-c-image"><a href="#"><img src="/images/post-thub2.jpg" alt=""></a></div>
          <div class="post-c-text">
            <h3><a href="#">Start an Event</a></h3>
            <p>Create your own event, and draw
              from a community of millions.</p>
            <h5><a href="#">start an event</a></h5>
          </div>
        </div>
      </div>
      <div>
        <div class="post-block">
          <div class="post-c-image"><a href="#"><img src="/images/post-thub.jpg" alt=""></a></div>
          <div class="post-c-text">
            <h3><a href="#">Discover events</a></h3>
            <p>See who’s hosting local events for all the
              things you love.</p>
            <h5><a href="#">JOIN OMECTO</a></h5>
          </div>
        </div>
      </div>
      <div>
        <div class="post-block">
          <div class="post-c-image"><a href="#"><img src="/images/post-thub2.jpg" alt=""></a></div>
          <div class="post-c-text">
            <h3><a href="#">Start an Event</a></h3>
            <p>Create your own event, and draw
              from a community of millions.</p>
            <h5><a href="#">start an event</a></h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section-follow">
  <div class="container">
    <h3>Follow Omecto</h3>
    <div class="follow"><a href="#"><img src="/images/utube.png" alt=""></a> <a href="#"><img src="/images/instagram.png" alt=""></a></div>
  </div>
</section>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB70MmakmCuRJl08Njf9z0Itv-nYf-DOPY&libraries=places"></script>
<script>
  function initialize() {
    var options = {
      types: ['(cities)'],
    };

    var input = document.getElementById('searchTextField');
    var autocomplete = new google.maps.places.Autocomplete(input, options);
  }

  google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/events/_modals.html.erb
<% @events.each do |event| %>
  <div class="modal events-popup" id="event<%= event.id %>" role="dialog" style="display: none;">
    <div class="modal-dialog new-modal">
      <div class="modal-content">
        <div class="modal-header no-border">
          <button type="button" class="close" data-dismiss="modal">×</button>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-5">
              <% if event.image.attached? %>
                <img src=<%= url_for(event.image) %> alt="">
              <% else %>
                <img src='/images/city26.jpg' alt="">
              <% end %>
            </div>
            <div class="col-md-7">
              <!-- <h3>Events Schedule</h3>
              <h4>sponsor club kim</h4> -->
              <h5><%= event.title %></h5>
              <p class="categories"><%= event.categories.length == 2 ? "#{event.categories[0].title}, #{event.categories[1].title}" : event.categories[0].title %></p>
              <p style="color:#000;"><%= "#{event.user.first_name} #{event.user.last_name}" %></p>
              <p class="greytext"><%= event.description %></p>
              <p><i class="fa fa-clock-o" aria-hidden="true"></i><%= event.date.strftime("%H:%M") %></p>
              <p><i class="fa fa-calendar-check-o" aria-hidden="true"></i><%= event.date.strftime("%-d %b %Y") %></p>
              <p class="text-uppercase mb-0"><i class="fa fa-map-marker" aria-hidden="true"></i><%= event.location.city %></p>
              <p class="text-uppercase"><i class="fa fa-map-marker fa-invisible" aria-hidden="true"></i><%= event.address %></p>
              <div class="join-event-<%= event.id %>">
                <% if user_signed_in? %>
                  <% if @participations.where(user_id: current_user.id, event_id: event.id).any? %>
                    <p>You already joined this event</p>
                  <% elsif current_user.id != event.user.id %>
                    <div class="row marg-top-10">
                      <div class="col-md-6 text-center">
                        <%= link_to new_participation_path(user_id: current_user.id, event_id: event.id), remote: true do %>
                          <img src="/images/join.jpg" alt="">
                        <% end %>
                      </div>
                      <div class="col-md-6 text-center">
                        <a href="javascript: void(0)" class="cancel-btn" data-dismiss="modal">Cancel</a>
                      </div>
                    </div>
                  <% end %>
                <% else %>
                  <div class="row marg-top-10">
                    <div class="col-md-6 text-center">
                      <%= link_to new_user_session_path do %>
                        <img src="/images/join.jpg" alt="">
                      <% end %>
                    </div>
                    <div class="col-md-6 text-center">
                      <a href="javascript: void(0)" class="cancel-btn" data-dismiss="modal">Cancel</a>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<section class="inner-banner"> <img src="/images/citybg.jpg" alt="">
  <section class="inner-banner-text">
    <h1><strong>Omecto</strong> Connects People Locally</h1>
    <p>Omecto is a platform for creating new connections anytime, anywhere in a formal or informal way. People use Omecto to host & join events,reach targeted audiences, meet new people, find support, solve a problem and pursue their passions, together.</p>
    <% unless user_signed_in? %>
      <%= link_to 'Join omecto', new_user_registration_path, class: 'joinbtn' %>
    <% end %>
  </section>
</section>
<section class="container">
  <section class="search-sec">
    <section class="search-sec1">
      <div class="row text-left">
        <div class="col">
          <%= form_tag "/events", method: :get, remote: true do %>
            <div class="row">
              <div class="col-md-3">
                <div class="search-div">
                  <%= text_field_tag :word, @word, placeholder: :search %>
                  <%= submit_tag("") %>
                </div>
              </div>
              <div class="col-md-6 search-text">
                в радиусе &nbsp;
                <%= select_tag :distance, options_for_select(@distances, @distance || 50), class: 'distance-field' %>
                &nbsp; от &nbsp;
                <%= text_field_tag :city, @city, placeholder: "Введите город", id: 'searchTextField', class: 'city-field' %>
              </div>
              <div class="col-md-3">
                <div class="col-md padd-0"><%= submit_tag("Искать", class: "groups-btn") %></div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </section>
  </section>
</section>
<section class="explore-city">
  <section class="container">
    <div class="row">
      <div class="col-md-6">
        <h3><a href="#">sort by best match</a></h3>
      </div>
      <div class="col-md-6 text-right">
        <h3><a href="#">explore more <img src="/images/arrow1.png" alt=""></a></h3>
      </div>
    </div>
    <section class="events-cate">
      <%= render 'events' %>
    </section>
  </section>
</section>
<div class="events-modals">
  <%= render 'modals' %>
</div>
<section class="join-social-sec">
  <section class="container">
    <section class="ome-join row m-0">
      <div class="col-lg-8 col-md-6 offset-lg-1">
        <h3>Find and Join Social</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
          Aenean euismod bibendum laoreet.</p>
      </div>
      <div class="col-lg-3 col-md-6 social-links"> <a href="#"><i class="fa fa-instagram"></i></a> <a href="#"><i class="fa fa-youtube"></i></a></div>
    </section>
  </section>
</section>
<section class="post-carousel">
  <div class="container-fluid">
    <h2>Want to do more of what you love?</h2>
    <div class="slider responsive">
      <div>
        <div class="post-block">
          <div class="post-c-image"><a href="#"><img src="/images/post-thub.jpg" alt=""></a></div>
          <div class="post-c-text">
            <h3><a href="#">Discover events</a></h3>
            <p>See who’s hosting local events for all the
              things you love.</p>
            <h5><a href="#">JOIN OMECTO</a></h5>
          </div>
        </div>
      </div>
      <div>
        <div class="post-block">
          <div class="post-c-image"><a href="#"><img src="/images/post-thub2.jpg" alt=""></a></div>
          <div class="post-c-text">
            <h3><a href="#">Start an Event</a></h3>
            <p>Create your own event, and draw
              from a community of millions.</p>
            <h5><a href="#">start an event</a></h5>
          </div>
        </div>
      </div>
      <div>
        <div class="post-block">
          <div class="post-c-image"><a href="#"><img src="/images/post-thub.jpg" alt=""></a></div>
          <div class="post-c-text">
            <h3><a href="#">Discover events</a></h3>
            <p>See who’s hosting local events for all the
              things you love.</p>
            <h5><a href="#">JOIN OMECTO</a></h5>
          </div>
        </div>
      </div>
      <div>
        <div class="post-block">
          <div class="post-c-image"><a href="#"><img src="/images/post-thub2.jpg" alt=""></a></div>
          <div class="post-c-text">
            <h3><a href="#">Start an Event</a></h3>
            <p>Create your own event, and draw
              from a community of millions.</p>
            <h5><a href="#">start an event</a></h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section-follow">
  <div class="container">
    <h3>Follow Omecto</h3>
    <div class="follow"><a href="#"><img src="/images/utube.png" alt=""></a> <a href="#"><img src="/images/instagram.png" alt=""></a> </div>
  </div>
</section>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB70MmakmCuRJl08Njf9z0Itv-nYf-DOPY&libraries=places"></script>
<script>
  // City autocomplete
  function initialize() {
    var options = {
      types: ['(cities)'],
    };

    var input = document.getElementById('searchTextField');
    var autocomplete = new google.maps.places.Autocomplete(input, options);
  }

  google.maps.event.addDomListener(window, 'load', initialize);

  // City field
  $('.city-field').click(function() {
    $(this).val('');
  });
</script>

app/views/events/new.html.erb
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>City:</strong>
  <%= @event.city %>
</p>

<p>
  <strong>Address:</strong>
  <%= @event.address %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/events/update_view.js.erb
$(".events-cate").html("<%= j render 'events' %>");
$(".events-modals").html("<%= j render 'modals' %>");

$(".city-field").val("<%= @city %>");