config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :blogs
  resources :events
  resources :categories, only: [:show]
  resources :participations, only: [:new]
  resources :connections, only: [:new]

  resources :conversations do
    resources :messages
  end

  devise_for :users
  resources :users, only: [:show]

  get 'welcome/index'
  get 'about', to: 'welcome#about'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
# frozen_string_literal: true

class Blog < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :event_categories
  has_many :events, through: :event_categories
end

app/models/connection.rb
# frozen_string_literal: true

class Connection < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'
end

app/models/conversation.rb
# frozen_string_literal: true

class Conversation < ActiveRecord::Base
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :between, lambda { |sender_id, recipient_id|
    where('(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)', sender_id, recipient_id, recipient_id, sender_id)
  }
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :user

  has_many :participations
  has_many :users, through: :participations

  belongs_to :location
  accepts_nested_attributes_for :location

  has_many :event_categories
  has_many :categories, through: :event_categories
  accepts_nested_attributes_for :event_categories

  has_one_attached :image
end

app/models/event_category.rb
# frozen_string_literal: true

class EventCategory < ApplicationRecord
  belongs_to :event
  belongs_to :category
end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord
  has_many :events

  geocoded_by :address
  after_validation :geocode

  def address
    city
  end
end

app/models/message.rb
# frozen_string_literal: true

class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime('%m/%d/%y at %l:%M %p')
  end
end

app/models/participation.rb
# frozen_string_literal: true

class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :events
  has_many :participations
  has_many :events, through: :participations
  has_many :blogs

  has_one_attached :image

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    first_name + ' ' + last_name
  end

  def image_url
    if image.attached?
      url_for(image)
    else
      '/images/user.png'
    end
  end
end

app/controllers/blogs_controller.rb
# frozen_string_literal: true

class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blogs = Blog.all.sample(3)
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit; end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def blog_params
    params.require(:blog).permit(:title, :user_id, :body, :image)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:show]

  def show
    senders = Connection.where(recipient_id: @user.id).map(&:sender_id)
    recipients = Connection.where(sender_id: @user.id).map(&:recipient_id)
    friends_ids = senders + recipients
    @friends = User.find(friends_ids)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/blogs_helper.rb
# frozen_string_literal: true

module BlogsHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/connections_helper.rb
# frozen_string_literal: true

module ConnectionsHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-3 info"> <a href="index.html"><img src="/images/f-logo.png" alt=""></a>
        <p>Omecto is a platform for creating new connections anytime, anywhere in a formal or informal way. People use Omecto to host & join events,reach targeted audiences, meet new people, find support, solve a problem and pursue their passions, together.</p>
      </div>
      <div class="col-md-3 info">
        <h3>Quick Links</h3>
        <ul>
          <li><a href="help.html">Help and Support</a></li>
          <li><a href="#">Terms And Conditions</a></li>
          <li><a href="privacy.html">Privacy And Policy</a></li>
        </ul>
      </div>
      <div class="col-md-3 info">
        <h3>Discover</h3>
        <ul>
          <% if user_signed_in? %>
            <li>
              <%= link_to 'Your Profile', user_path(current_user) %>
            </li>
            <li>
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Sign Up', new_user_registration_path %>
            </li>
            <li>
              <%= link_to 'Login', new_user_session_path %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="col-md-3 info">
        <h3>Our Details</h3>
        <p>Omecto Connects People Locally</p>
        <address>
        <p><i class="fa fa-map-marker"></i> Kiev-Ukraine</p>
        <p><i class="fa fa-phone"></i> +38(0) 97 834 68 99</p>
        <p><i class="fa fa-envelope"></i> support@omecto.com</p>
        </address>
      </div>
    </div>
  </div>
  <div class="copyright"><a href="#"><i class="fa fa-instagram"></i></a> <a href="#"><i class="fa fa-youtube"></i></a>
    <p>&copy; 2019 Omecto. Omecto is a wholly owned subsidiary of WeWork Companies Inc.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="container">
    <div class="icon-menu"><i class="fa fa-bars"></i></div>
    <figure class="logo"> <a class="navbar-brand" href="/"><img src="/images/logo.png" alt="Omecto" title="Omecto"></a> </figure>
    <div class="group-sign">
      <ul class="d-flex align-items-center">
        <li><a href="#">upgrade now</a></li>
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user) do %>
              <i class="fa fa-user"></i>
              <%= current_user.full_name %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>
              Sign Out
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_session_path do %>
              <i class="fa fa-user"></i>
              Login
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path do %>
              <i class="fa fa-user-plus"></i>
              Sign up
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="group-element d-flex">
      <%= link_to "events", events_path, class: "btn-socials" %>
      <%= link_to "Create an event", new_event_path, class: "btn-event" %>
      <div class="notify">
        <ul>
          <li><a href="#"><i class="fa fa-bell-o"></i></a></li>
          <li><a href="#"><i class="fa fa-envelope-o"></i></a></li>
          <li><a href="#"><i class="fa fa-user-o"></i></a>
            <% if user_signed_in? %>
              <div class="profile-drop">
                <a href="#"><span class="d-icon"><i class="fa fa-user" aria-hidden="true"></i></span> my profile</a>
                <a href="#"><span class="d-icon"><i class="fa fa-edit" aria-hidden="true"></i></span> edit profile</a>
                <a href="#"><span class="d-icon"><i class="fa fa-instagram" aria-hidden="true"></i></span> my socials</a>
                <a href="#"><span class="d-icon"><i class="fa fa-sign-out" aria-hidden="true"></i></span> logout</a>
              </div>
            <% end %>
          </li>
        </ul>
      </div>
      <a class="search1" href="#"><i class="fa fa-search"></i></a> </div>
  </div>
  <div class="event-btn-group">
   <div class="container">
    <%= link_to "Create an event", new_event_path %>
    <%= link_to "events", events_path %>
   </div>
  </div>  
</header>
<nav class="navigation">
  <div class="icon-close"><a>CLOSE</a><i class="fa fa-close"></i> </div>
  <ul>
    <li><%= link_to "Blog", blogs_path %></li>
    <li><%= link_to "About", about_path %></li>
  </ul>
  <div class="group-mobile-btn">
    <% if user_signed_in? %>
      <%= link_to 'sign out', destroy_user_session_path, method: :delete, class: 'btn-event' %>
    <% else %>
      <%= link_to :login, new_user_session_path, class: 'btn-event' %>
      <%= link_to 'sign up', new_user_registration_path, class: 'btn-event' %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Omecto</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link rel="icon" type="image/png" href="/favicon.png">
  <link href="/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="/css/jquery.fancybox.css" media="screen" />
  <link href="/css/bootstrap.min.css" rel="stylesheet">
  <link href="/css/imagehover.css" rel="stylesheet" media="all">
  <link href="/css/style.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,400i,500,700,700i,900&display=swap" rel="stylesheet">
  <link href="/css/responsive.css" rel="stylesheet">
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
  <script>
           document.createElement('header');
           document.createElement('section');
           document.createElement('article');
           document.createElement('aside');
           document.createElement('nav');
           document.createElement('footer');
        </script>
  <script src="/js/jquery-1.11.0.min.js"></script>
  <script src="/js/bootstrap.min.js"></script>
  <script src="/js/jquery.bxslider.js"></script>
  <script type="text/javascript" src="/js/slick.js"></script>
  <script type="text/javascript" src="/js/scripts.js"></script>
  <script type="text/javascript" src="/js/jquery.fancybox.js"></script>
  <script>
    $(document).ready(function(){
      $('.bxslider').bxSlider({
        mode: 'fade',
        pagerCustom: '#bx-pager',
        adaptiveHeight: true
      });
      $('.bannerslider').bxSlider({
        mode: 'horizontal',
        moveSlides: 1,
        slideMargin: 40,
        infiniteLoop: true,
        auto: true,
        minSlides: 1,
        maxSlides: 1,
        speed: 800,
     });
      $('.grouplider').bxSlider({
        mode: 'horizontal',
        moveSlides: 1,
        slideMargin: 40,
        infiniteLoop: true,
        auto: true,
        minSlides: 1,
        maxSlides: 1,
        speed: 600,
        autoDelay: 500,
     });
       
    });
  </script>
  <script type="text/javascript">
      $(document).ready(function() {
        $('.fancybox').fancybox();
      });
  </script>
  <script>
      var main = function() {   
          $('.icon-menu').click(function() {
              $('.navigation').animate({
                  left: "0px"
              }, 200);
              $('body').animate({
                  left: "285px"
              }, 200);
          });
          $('.icon-close').click(function() {
              $('.navigation').animate({
                  left: "-285px"
              }, 200);
              $('body').animate({
                  left: "0px"
              }, 200);
          });
      };
  $(document).ready(main);
  </script>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>